FROM node:12-alpine
LABEL name "Cyborg Bot"
LABEL version "0.1.0"
LABEL maintainer "Corteez#3113"
ARG VERSION
ENV NODE_ENV= \
    TOKEN= \
    OWNER= \
    COMMAND_PREFIX= \
    LOGS= \
    NODE_ENV= \
    GRAPHQL_ENDPOINT= \
    HASURA_GRAPHQL_ADMIN_SECRET= \
WORKDIR=/cyborg
COPY src/bot/package.json /cyborg/src/bot/
COPY package.json /cyborg/
RUN npm install
COPY . .
CMD ["node", "src/bot/dist/bot.js"]