FROM node:12-alpine
LABEL name "Cyborg Bot"
LABEL version "0.1.0"
LABEL maintainer "Corteez#3113"
ARG VERSION
ENV NODE_ENV= \
    TOKEN= \
    OWNER= \
    COMMAND_PREFIX= \
    LOGS= \
    NODE_ENV= \
    GRAPHQL_ENDPOINT= \
    HASURA_GRAPHQL_ADMIN_SECRET= \
WORKDIR /usr/Cyborg
COPY src/bot/package.json /usr/Cyborg/src/bot/
COPY package.json /usr/Cyborg/
RUN apk add --update \
&& apk add --no-cache ca-certificates \
&& apk add --no-cache --virtual .build-deps git curl build-base python g++ make \
&& curl -L https://unpkg.com/@pnpm/self-installer | node \
&& pnpm i \
&& apk del .build-deps
COPY . .
RUN pnpm recursive run build --filter bot
CMD ["node", "src/bot/dist/bot.js"]